version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: warehouse_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse_kopi
    ports:
      - "55432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: warehouse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@warehouse.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres